collections:
- name: community.general
  version: 9.0.0
- name: kubernetes.core
  version: 4.0.0
- name: operator_sdk.util
  version: 0.5.0
- name: ansible.posix
  version: 1.6.2
- name: ansible.builtin
